### ISSUE TITLE
Mapping PineAPPL to NNPDF

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/runcards#115]
during the benchmark we realized that the metadata to identify the NNPDF counterpart to a PineAPPL grid is not sufficient:

- there are many PineAPPL grids mapping to a single NNPDF grid: e.g.:
  ```
  nnpdf_info = nnpdf_data("LHCBWZMU7TEV", "NNPDF30_nnlo_as_0118")
  corresponding_pineappls = ["LHCB_DY_7TEV", "LHCB_WP_7TEV","LHCB_WM_7TEV"]
  ```
  ( taken from https://github.com/NNPDF/tutorials/blob/master/pineappl/Create%20new%20cfactor%20files%20with%20pineappl%20-%20Pineappl%20python%20interface%20test%20case.ipynb - thanks @scarlehoff (and he said the only way of finding the correct order is by trying every one ... :upside_down_face:  ) )
  I need a way to resolve this and my proposal would be to add a `nnpdf_bin_offset` to the metadata that determines the starting bin in NNPDF and then the bins in PineAPPL should be in `NNPDF[nnpdf_bin_offset:nnpdf_bin_offset + len(bins)]` - would this work?
- And there is the additional problem, that there are several runcards for a single PineAPPL grid that need to be merged *after* generation - e.g. https://github.com/NNPDF/runcards/tree/master/nnpdf31_proc/ATLAS_DY_7TEV_CC_046_066
  that has a non-trivial interplay with the first point since `merge` needs to preserve that information; at the moment `merge` is preserving the information from the first grid (I think @AleCandido ) and maybe this is sufficient? (since the bins are hopefully consecutive ...)

**Comment by scarlehoff** [comment]
> and he said the only way of finding the correct order is by trying every one

The only way I know of!

>  that determines the starting bin in NNPDF [...] would this work?

Yes _but_ I would just do the order (name, table_idx=i) because the bins are too sensible and don't really matter*.
And in practice you are going to still do:

```python
nnpdf_idx = nnpdf.function_that_give_indices()
pineappl_total = function_that_concatenates([pine1, pine2, pine3])
pineappl_by_nnpdf_indicies = pineappl_total[nnpdf_idx]
```

Why would I do it in that order? Because the NNPDF array is a pandas dataframe where not necessarily all points are contained and so this

```python
NNPDF[nnpdf_bin_offset:nnpdf_bin_offset + len(bins)]
```

will fail unless there isn't a call to `function_that_converts_sparse_to_dense_array` before.**

*of course, the order is contained in the specific bins (because the order is just a sort by starting bin)

**and you could say "but points are always cut from the beggining or end of the dataset, right?" but the answer is "most of the time but I wouldn't count on that, the other solution is more robust"

**Comment by cschwan** [comment]
If we add metadata I'd add `nnpdf_id_subset` which can be set to `0`, `1`, `2`, ... that uniquely defines the ordering. 

However, in the long term, I'd rework the way data is implemented in such a way that this becomes obsolete. Maybe we can have NNPDF IDs of the form `nnpdf_id=LHCBWZMU7TEV.Z`, `nnpdf_id=LHCBWZMU7TEV.WP` and `nnpdf_id=LHCBWZMU7TEV.WM` such that validphys recognizes the three belong to the same set `LHCBWZMU7TEV` but nevertheless makes it trivial to implement and associate the different data with.

**Comment by felixhekhorn** [comment]
I think for the moment = benchmarking, I will do as @scarlehoff said and introduce again some handcrafted settings (and iterating over NNPDF e.g. instead etc.) - we can (should) improve in the future maybe nevertheless
